In [9]:
import numpy as np
import matplotlib.pyplot as plt
%run constants.py

In [14]:
if dataset == 'HIGGS':
    inputfile = 'datasets/HIGGS.csv'
else:
    inputfile = 'datasets/SUSY.csv'
inputfile = 'datasets/HIGGS.csv'
X = np.loadtxt(inputfile, dtype='f4', delimiter=',')

# y = X[:,0].reshape((-1,1))
# X = X[:,1:]
# X = np.array(X, dtype='float32')
# y = np.array(y, dtype='float32')
# if benchmark == 1:
#     # HIGGS
#     ntrain = 10000000 
#     nvalid = 500000 
#     ntest  = 500000
# elif benchmark == 2:
#     # SUSY
#     ntrain = 4000000 
#     nvalid = 500000 
#     ntest  = 500000

In [15]:
y = X[:,0].reshape((-1,1))
X = X[:,1:]

In [16]:
len(y)


11000000

In [17]:
y[1:3]

array([[1.],
       [1.]], dtype=float32)

In [20]:
X

array([[ 0.8692932 , -0.6350818 ,  0.22569026, ...,  0.72165745,
         0.98875093,  0.87667835],
       [ 0.9075421 ,  0.32914728,  0.35941187, ...,  0.77973217,
         0.99235576,  0.7983426 ],
       [ 0.79883474,  1.4706388 , -1.6359748 , ...,  0.8032515 ,
         0.8659244 ,  0.7801176 ],
       ...,
       [ 0.7005588 ,  0.77425104,  1.5201818 , ...,  1.8884383 ,
         1.1537658 ,  0.9312791 ],
       [ 1.1780295 ,  0.11779606, -1.2769796 , ...,  0.33970493,
         0.7590703 ,  0.7191192 ],
       [ 0.46447706, -0.33704734,  0.22901943, ...,  0.57608366,
         0.54142696,  0.5174199 ]], dtype=float32)

In [21]:
np.split(X, 100)

[array([[ 0.8692932 , -0.6350818 ,  0.22569026, ...,  0.72165745,
          0.98875093,  0.87667835],
        [ 0.9075421 ,  0.32914728,  0.35941187, ...,  0.77973217,
          0.99235576,  0.7983426 ],
        [ 0.79883474,  1.4706388 , -1.6359748 , ...,  0.8032515 ,
          0.8659244 ,  0.7801176 ],
        ...,
        [ 0.70330393,  0.46842483,  0.8288245 , ...,  1.487255  ,
          0.8840115 ,  0.78343564],
        [ 0.6533425 , -1.0490185 ,  0.9603267 , ...,  0.5675625 ,
          0.6111431 ,  0.6085196 ],
        [ 0.69232345, -1.1035607 , -1.6082318 , ...,  0.7898097 ,
          0.9300012 ,  0.8309017 ]], dtype=float32),
 array([[ 1.5511851 ,  0.7664593 ,  1.2011365 , ...,  0.78386825,
          0.8149229 ,  0.6929147 ],
        [ 0.73478156, -0.16465487,  0.18352082, ...,  1.0228488 ,
          0.91608703,  0.8386074 ],
        [ 1.5865059 ,  2.0004776 , -1.479504  , ...,  1.1452098 ,
          0.91045666,  0.95029604],
        ...,
        [ 0.7062321 , -0.4695071 ,  1.3

In [22]:
X.shape


(11000000, 28)

In [23]:
y.shape


(11000000, 1)

In [46]:

qwe

array([[ 7.9883474e-01,  1.4706388e+00, -1.6359748e+00,  4.5377317e-01,
         4.2562917e-01,  1.1048746e+00,  1.2823223e+00,  1.3816643e+00,
         0.0000000e+00,  8.5173720e-01,  1.5406590e+00, -8.1968951e-01,
         2.2148721e+00,  9.9348992e-01,  3.5608011e-01, -2.0877755e-01,
         2.5482244e+00,  1.2569546e+00,  1.1288476e+00,  9.0046084e-01,
         0.0000000e+00,  9.0975326e-01,  1.1083305e+00,  9.8569220e-01,
         9.5133126e-01,  8.0325150e-01,  8.6592442e-01,  7.8011757e-01],
       [ 1.3443848e+00, -8.7662601e-01,  9.3591273e-01,  1.9920501e+00,
         8.8245440e-01,  1.7860659e+00, -1.6467777e+00, -9.4238251e-01,
         0.0000000e+00,  2.4232647e+00, -6.7601579e-01,  7.3615867e-01,
         2.2148721e+00,  1.2987198e+00, -1.4307381e+00, -3.6465818e-01,
         0.0000000e+00,  7.4531269e-01, -6.7837882e-01, -1.3603563e+00,
         0.0000000e+00,  9.4665247e-01,  1.0287037e+00,  9.9865609e-01,
         7.2828060e-01,  8.6920023e-01,  1.0267365e+00,  9.5790

In [51]:
np.random.shuffle(qwe)


In [52]:
qwe


array([[ 9.0754211e-01,  3.2914728e-01,  3.5941187e-01,  1.4979699e+00,
        -3.1300953e-01,  1.0955306e+00, -5.5752492e-01, -1.5882298e+00,
         2.1730762e+00,  8.1258118e-01, -2.1364193e-01,  1.2710146e+00,
         2.2148721e+00,  4.9999395e-01, -1.2614318e+00,  7.3215616e-01,
         0.0000000e+00,  3.9870089e-01, -1.1389301e+00, -8.1911020e-04,
         0.0000000e+00,  3.0221990e-01,  8.3304816e-01,  9.8569965e-01,
         9.7809839e-01,  7.7973217e-01,  9.9235576e-01,  7.9834259e-01],
       [ 7.9883474e-01,  1.4706388e+00, -1.6359748e+00,  4.5377317e-01,
         4.2562917e-01,  1.1048746e+00,  1.2823223e+00,  1.3816643e+00,
         0.0000000e+00,  8.5173720e-01,  1.5406590e+00, -8.1968951e-01,
         2.2148721e+00,  9.9348992e-01,  3.5608011e-01, -2.0877755e-01,
         2.5482244e+00,  1.2569546e+00,  1.1288476e+00,  9.0046084e-01,
         0.0000000e+00,  9.0975326e-01,  1.1083305e+00,  9.8569220e-01,
         9.5133126e-01,  8.0325150e-01,  8.6592442e-01,  7.8011